title: Ynda Jas
description: "They/them. Queer non-binary transfemme activist, socialist, creative, lapsed academic and developing coder."
author: "Ynda Jas"
facebook: yndajascreative
instagram: yndajas
twitter: yndajas
linkedin: yndajas
github: yndajas
soundcloud: yndajas
behance: yndajas
playstation: yndajas
analytics_id: UA-121898351-1
menu:
  - text: Home
    url: /
  - text: Name
    url: /name/
  - text: Activism
    url: /activism/
  - text: Academia
    url: /academia/
  - text: "Professional experience"
    url: /professional/
  - text: Blog
    url: /blog/
  - text: Contact
    url: /contact/
permalink: pretty
url: https://yndajas.co
enforce_ssl: yndajas.co
plugins:
  - "jekyll-sitemap"
  - "jekyll-feed"
