title: Ynda Jas
description: "Ynda Jas is a queer non-binary activist, academic and creative. Pronouns: they/them/their."
author: "Ynda Jas"
facebook: yndajascreative
instagram: yndajas
twitter: yndajas
linkedin: yndajas
soundcloud: yndajas
behance: yndajas
analytics_id: UA-121898351-1
menu:
  - text: Home
    url: /
  - text: Pronunciation
    url: /pronunciation/
  - text: "Academia&#58;"
    url: /academia/
  - text: "> Research"
    url: /academia/research/
  - text: "> Teaching"
    url: /academia/teaching/
  - text: "> Education"
    url: /academia/education/
  - text: Activism
    url: /activism/
  - text: "Professional experience"
    url: /professional/
  - text: Citation
    url: /citation/
  - text: Blog
    url: /blog/
permalink: pretty
url: https://yndajas.co
enforce_ssl: yndajas.co
plugins:
  - "jekyll-sitemap"
  - "jekyll-feed"
