title: Ynda Jas
description: "Ynda Jas is a queer non-binary activist, creative and academic. Pronouns: they/them/their."
author: "Ynda Jas"
facebook: yndajascreative
instagram: yndajas
twitter: yndajas
analytics_id: UA-121898351-1
menu:
  - text: Home
    url: /
  - text: Pronunciation
    url: /pronunciation/
  - text: Academia
    url: /academia/
  - text: Blog
    url: /blog/
permalink: pretty
url: https://yndajas.co
enforce_ssl: yndajas.co
plugins:
  - "jekyll-sitemap"
